def imageName = "YOURID/IMAGENAME"
def tagName = "TAGNAME"

def elyraContainerName = "elyra-container"
def confName = "kfp-config.json"
def pipName = "YOURPIPELINENAME.pipeline"

pipeline {
	agent any
	stages {
		stage('Git Clone') {
			steps {
				git branch: 'master', url: 'https://github.com/Woo-Dong/mlops-lecture.git'
			}
		}
		stage("Docker Build") {
			steps {
				script {
					sh "docker build -t ${imageName}:${tagName} ."
				}
			}
		}
		stage("Docker Push") {
			steps {
				script {
					sh "docker push ${imageName}:${tagName}"
				}
			}
		}
    	stage("Set Elyra Runtimes") {
			steps {
				script {
					sh """docker exec -i -w \$(pwd) ${elyraContainerName} \
						elyra-metadata create runtimes \
							--file ${confName} \
						|| echo 'elready exists - runtimes ${confName}'
					"""
				}
			}
		}
    	stage("Submit Elyra API") {
			steps {
				script {
					sh """docker exec -i -w \$(pwd) ${elyraContainerName} \
						elyra-pipeline submit ${pipName} \
							--runtime-config kfp-config \
							--json --monitor \
							--monitor-timeout 60
					"""
				}
			}
		}
	}
}
