// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4IcgKSTdFROlvwANUOt6ImiSU0WgZucg',
    appId: '1:221051241412:web:1dea670f5ab7488d295a91',
    messagingSenderId: '221051241412',
    projectId: 'firstline-17bda',
    authDomain: 'firstline-17bda.firebaseapp.com',
    databaseURL: 'https://firstline-17bda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firstline-17bda.appspot.com',
    measurementId: 'G-39GFTKSBV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ0Iy0kxbx_4m8UDL88LZumGxXR7VweeU',
    appId: '1:221051241412:android:c65f6c26c4618928295a91',
    messagingSenderId: '221051241412',
    projectId: 'firstline-17bda',
    databaseURL: 'https://firstline-17bda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firstline-17bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqayZqNUo6il07pD_QJcf-9HX0RAuY2Es',
    appId: '1:221051241412:ios:ca9589f30713056b295a91',
    messagingSenderId: '221051241412',
    projectId: 'firstline-17bda',
    databaseURL: 'https://firstline-17bda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firstline-17bda.appspot.com',
    iosBundleId: 'com.example.firstLineFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqayZqNUo6il07pD_QJcf-9HX0RAuY2Es',
    appId: '1:221051241412:ios:8201370d5f2130f4295a91',
    messagingSenderId: '221051241412',
    projectId: 'firstline-17bda',
    databaseURL: 'https://firstline-17bda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firstline-17bda.appspot.com',
    iosBundleId: 'com.example.firstLineFirebase.RunnerTests',
  );
}
